version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  bitcoin-price-service:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=3000
      - UPDATE_FREQUENCY=10000
      - SERVICE_COMMISSION=0.0001
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis